baseURL = "https://caiplusplus.github.io/"
languageCode = "zh-cn"
title = "菜可以"
theme = "ananke"
hasCJKLanguage = true
summaryLength = 30

[params]
  description = "技术学习笔记与日常分享"
  favicon = ""
  site_logo = ""
  background_color_class = "bg-black"
  featured_image = "/images/header.jpg"
  recent_posts_number = 5

[menu]
  [[menu.main]]
    name = "首页"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "博客"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "分类"
    url = "/categories/"
    weight = 3
  [[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 4

[taxonomies]
  category = "categories"
  tag = "tags" 